### ISSUE TITLE
Como actualizar la DB

### ISSUE THREAD

**Issue by powermx** [wallyqs/covid19mx#1]
Hola que tal, duda, como actualizar la base de datos ?

Saludos, excelente trabajo.

**Comment by wallyqs** [comment]
Gracias espero que haya sido algo útil... no hay base de datos porque los datos se extraen directamente del mapa que publican en las conferencias todos los días pero aquí están algunos datos pasados: https://github.com/wallyqs/covid19mx/tree/master/data
Otros repositorios tienen mejor colección de estos datos como https://github.com/guzmart/covid19_mex o http://covidatos.mx/ pero esta herramienta por el momento solo dice los datos del día de hoy y ayer...
